### ISSUE TITLE
[Junior] Roadmap do desenvolvedor junior.

### ISSUE THREAD

**Issue by odenirdev** [opensource-courses/courses#17]
A ideia desse conteúdo, é criar um roadmap(guia) para desenvolvedores júnior e iniciantes:

- Onboarding do dev a área de programação
- Softskills de um dev profissional
- Overview do roadmap devjr
- Link para as trilhas

Criar um roadmap parecido com o os roadmaps criados no projeto [kamranahmedse/developer-roadmap](https://github.com/kamranahmedse/developer-roadmap), só que para iniciantes, roadmap que não existe no projeto.

**Comment by odenirdev** [comment]
Fala galera, estou conversando com alguns de vocês, convidando para pesquisar e escrever esse conteúdo em conjunto.

Quem tiver interesse de fazer uma call, fica vontade em entrar em contato comigo.

Ainda estou preparando a ideia principal principal do conteúdo, o impacto que tem que causar. Mas acho que uma abordagem alinhada com o objetivo do projeto é ele ser uma Guia Prático, trazendo incentivo, teoria e um caminho prático para o desenvolvedor seguir.

Também estou lendo algumas referências para o conteúdo ter embasamento.

Artigo "Como se tornar um programador em 10 anos" do Peter Norvig.

Livro "Guia Front-End - O caminho das pedras para ser um dev Front-End" do Diego Eis.

**Comment by Ceagah** [comment]
Opa! Tenho interesse @odenirdev !
E tenho algumas ideias ! Podemos conversar nessa segunda dia 12/09 ?

**Comment by nycolexavier** [comment]
Opa, também tenho interesse!

**Comment by odenirdev** [comment]
Fala galera, muito obrigado pelo interesse, me chamem pelo Linkedin por favor para marcarmos um horário.

**Comment by odenirdev** [comment]
Sua solicitação de conteúdo está relacionada a um problema? Por favor descreva. Uma descrição clara e concisa do que é o problema. Ex. Eu sempre fico frustrado quando [...]

Quando estava iniciando a estudar programação me sentia perdido e a cada monte de conhecimento que adquiria me deparava com um outra montanha de conhecimento. O guia prático da pessoa programadora iniciante, tem o objetivo de guiar os iniciantes em programação sobre os principais assuntos, teoria e ferramentas em tecnologia. Ajudando os iniciantes a ter uma escalada objetiva e performática nos estudos em TI.

Descreva o conteúdo desejado Uma descrição clara e concisa do que você quer que aconteça.

Guia prático para pessoas ingressarem ao mercado de tecnologia.

Apresentando assuntos, dicas e ferramentas  para iniciar na programação.

Descreva as alternativas que você considerou para o conteúdo Uma descrição clara e concisa de conteúdo que você considerou.

- [ ]  Boas vindas, escalada de conhecimento e comunidade - Criar um cronograma de estudo
- [ ]  Solucionador de problemas - Exercitar raciocínio lógico
- [ ]  Mercado e oportunidades - Criar um post compartilhando sua jornada

Contexto adicional Adicione qualquer outro contexto ou capturas de tela sobre a solicitação de conteúdo aqui.

Em Boas vindas, recepcionar a pessoa iniciante de forma calorosa. Falar sobre disciplina e constância para se manter em constante evolução em TI. Falar sobre como ser manter motivado e receber ajuda da comunidade.

Em Solucionador de problemas, falar sobre a principal função de uma pessoa programadora que é solucionar problemas da sociedade utilizando tecnologia como ferramenta. Para ser um melhor solucionador de problemas é preciso ter um repertório de soluções, apresentar uma forma de começar a criar experiência praticando o raciocínio lógico para se tornar um melhor solucionador de problemas.

Em mercado apresentar as oportunidades de mercado e como aumentar o alcance de oportunidades.

**Comment by matheusm** [comment]
Muito bom @odenirdev ! Acredito que está bem completo, seria possível adicionar na parte de solucionador de problemas algo mais focado em lógica computacional ao invés de raciocínio lógico? De resto está tudo perfeito! 👏🏻 👏🏻

**Comment by Joao-mello-ferrari** [comment]
Achei excelente @odenirdev! Acho que este formato está ideial. Concordo com o @matheusm, que fala sobre adicionar, também, lógica computacional. Parabéns pelo trabalho!

**Comment by odenirdev** [comment]
Fala pessoal, muito obrigado pelos comentários essas discussões, que vão fazer o conteúdo ser mais completo.

Sobre a lógica computacional é muito importante mesmo, saber como que funciona por baixo dos panos, por sorte já temos um conteúdo próprio do projeto feito pelo @Joao-mello-ferrari, vejo isso como um super diferencial, mas lógica de programação e raciocínio lógico são habilidades eu diria são obrigatórias.

Lógico, podemos citar a importância de se aprimorar, conhecer como que roda por baixo dos panos e encaminhar para o conteúdo incrível que o João contribuiu

**Comment by odenirdev** [comment]
Fala pessoal, to me divertindo muito escrevendo artigos pra cá, espero incentivar vocês a contribuirem também!

Quem tem me acompanhado pelo instagram @_odenirdev, já sabe porque contei por lá que estava escrevendo um novo artigo, a segunda parte do Guia  **Solucionador de problemas - Exercitar raciocínio lógico**.

Já comecei a fase de pesquisar, estruturar e direção criativa para o artigo. Decidi chamar essa segunda parte como "A arte para solucionar problemas", por muita coincidência encontrei um material perfeito. O livro que encontrei é o **The Art of Reasoning: An Introduction to Logic and Critical Thinking** escrito por David Kelley, doutor em filosofia pela Universidade de Princeton e lecionou no Vassar College e na Brandeis University. Ele escreveu esse livro para ser um materia introdutorio para os calouros nas universidades, explicando o básico sobre padrões de um bom pensamento.

Tô estudando e me divertindo muito com esse conteúdo, tem me ensinado muito sobre raciocínio e lógica! Vou continuar pesquisando sobre lógica e pensamento crítico, quem quiser discutir sobre o assunto, por favor, comente aqui nessa issue 👇🏾
